services:
  - type: web
    name: gugulabo
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
